[workspace]
authors = ["Akayou Adane Kitessa <akuadane1205@gmail.com>"]
channels = ["conda-forge"]
name = "my-agent"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
format = "ruff format ."
lint = "ruff check ."
pytest = "pytest"
setup = "pre-commit install"


[dependencies]
python = "3.11.*"
pre-commit = ">=4.6.0,<5"

[pypi-dependencies]
pytest = ">=9.0.3, <10"
ruff = ">=0.15.11, <0.16"
mypy = ">=1.20.2, <2"
llmx = ">=0.0.21a0, <0.0.21a1"
colorama = ">=0.4.6, <0.5"
hatchling = ">=1.27.0, <2"
agentlib = { path = ".", editable = true }
pyttsx3 = ">=2.99, <3"
